import localFont from "next/font/local";
import "./globals.css";
import Chatbot from "../components/Chatbot";
import Header from "../components/Navbar"; // Import your Header component
import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import { auth } from "../auth";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const setInitialTheme = `
  (function() {
    const savedTheme = localStorage.getItem('theme');
    if (savedTheme === 'dark') {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  })();
`;

  const session = await auth();
  return (
    <SessionProvider session={session}>
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Inject the theme script to apply dark mode instantly */}
       <script dangerouslySetInnerHTML={{ __html: setInitialTheme }} />
        <Header /> {/* Render the Header here */}
        <Toaster />
        {children}
        {/* <Chatbot /> */}
      </body>
    </html>
    </SessionProvider>
  );
}
